set autoread
set nocompatible   		        " We don't have to be compatible with the basic vi
set laststatus=2   " Always show the statusline
set backspace=indent,eol,start  	" Allow backspacing over everything in the insert mode
set nobackup
set nowb
set noswapfile
set history=1000
set nocp
set encoding=utf-8 			" Necessary to show unicode glyphs
set t_Co=256 				" Explicitly tell vim that the terminal supports 256 colors

" Bundles
" -----------------------------------------------------------------------------

filetype off

set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" let Vundle manage Vundle
" required! 
Bundle 'gmarik/vundle'

" Trying theese

Bundle 'Lokaltog/vim-powerline'
Bundle 'mutewinter/vim-indent-guides'

" General
Bundle 'mileszs/ack.vim'
Bundle 'vim-scripts/local_vimrc.vim'
Bundle 'xolox/vim-session'

Bundle 'rphillips/vim-zoomwin'		
Bundle 'kien/ctrlp.vim'			
Bundle 'scrooloose/nerdtree'		
Bundle 'scrooloose/nerdcommenter'	
Bundle 'sickill/vim-pasta'		
Bundle 'tpope/vim-fugitive'		
Bundle 'scrooloose/syntastic'
Bundle 'vim-scripts/scratch.vim'

" General text editing
Bundle 'msanders/snipmate.vim'		
Bundle 'tsaleh/vim-align'
Bundle 'tpope/vim-surround'		
Bundle 'ervandew/supertab'

" Ruby, Rails et al
Bundle 'vim-ruby/vim-ruby'
Bundle 'tpope/vim-rails'		
Bundle 'tpope/vim-cucumber'		
Bundle 'tpope/vim-haml'			
Bundle 'skalnik/vim-vroom'		

" JavaScript, CoffeeScript etc
Bundle 'pangloss/vim-javascript'
Bundle 'kchmck/vim-coffee-script'

" C/C++
Bundle 'vim-scripts/OmniCppComplete'
Bundle 'vim-scripts/a.vim'

" Other file formats
Bundle 'mutewinter/taskpaper.vim'
Bundle 'tpope/vim-markdown'		
Bundle 'acustodioo/vim-tmux'
Bundle 'msanders/cocoa.vim'

syntax on				

let mapleader=","
let g:mapleader =","


set tags+=$CODE_TAGS

" UI
" -----------------------------------------------------------------------------

set ruler          " Ruler on
set nu 		         " Line numbers on
set nowrap         " Line wrapping off
set cmdheight=2    " Make the command area two lines high
set encoding=utf-8
if exists('+colorcolumn')
	set colorcolumn=80 " Color the 80th column differently
endif

set showmatch   " Show matching brackets.
set matchtime=2 " How many tenths of a second to blink

colorscheme Tomorrow-Night-Bright
:set background=dark

" Text Format
" -----------------------------------------------------------------------------
set tabstop=2
set backspace=2  " Delete everything with backspace
set shiftwidth=2 " Tabs under smart indent
set cindent
set autoindent
set smarttab
set expandtab

" Enable filetype plugin
filetype plugin on
filetype indent on
  
" When vimrc is edited, reload it
autocmd! bufwritepost vimrc source ~/.vim/vimrc

" Use Ack instead of grep
set grepprg=ack                 

set background=dark
" Set colors for indent-guide
hi IndentGuidesOdd  guibg=red   ctermbg=black
hi IndentGuidesEven guibg=green ctermbg=darkgrey

" Keys
" -----------------------------------------------------------------------------

" Fixing common typos
command! W w
command! Q q

" Move around splits with <c-hjkl>
nnoremap <c-j> <c-w>j
nnoremap <c-k> <c-w>k
nnoremap <c-h> <c-w>h
nnoremap <c-l> <c-w>l

set pastetoggle=<F2>

" Plugin specific:
" -----------------------------------------------------------------------------
function! InsertTabWrapper()
    let col = col('.') - 1
    if !col || getline('.')[col - 1] !~ '\k'
        return "\<tab>"
    else
        return "\<c-p>"
    endif
endfunction
inoremap <tab> <c-r>=InsertTabWrapper()<cr>
inoremap <s-tab> <c-n>

" => NERDTree
nnoremap <leader>nn :NERDTreeToggle<CR>
nnoremap <leader>nf :NERDTreeFind<CR>
let NERDTreeShowBookmarks=1
let NERDTreeChDirMode=2 " Change the NERDTree directory to the root node
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif
autocmd vimenter * if !argc() | NERDTree | endif    " Automatically open NERDtree, if vim launched w/o files specified

" => NERDCommenter
map <leader>/ <plug>NERDCommenterToggle<CR>
imap <leader>/ <Esc><plug>NERDCommenterToggle<CR>i

" => ZoomWin
map <up><up> :ZoomWin<CR>

" => PowerLine
let g:Powerline_symbols = 'fancy'
let g:Powerline_cache_enabled = 1
call Pl#Theme#InsertSegment('ws_marker', 'after', 'lineinfo')

" => IndentGuides
let indent_guides_guide_size=1
let indent_guides_start_level=2

" => vim-scratch
map <down><down> :Sscratch<CR>
autocmd FileType cpp set omnifunc=omni#cpp#complete#Main

" => a.vim
map <C-S-Up> :A<CR>

" => OmniCppComplete
" OmniCppComplete
let OmniCpp_NamespaceSearch = 1
let OmniCpp_GlobalScopeSearch = 1
let OmniCpp_ShowAccess = 1
let OmniCpp_ShowPrototypeInAbbr = 1 " show function parameters
let OmniCpp_MayCompleteDot = 1 " autocomplete after .
let OmniCpp_MayCompleteArrow = 1 " autocomplete after ->
let OmniCpp_MayCompleteScope = 1 " autocomplete after ::
let OmniCpp_DefaultNamespaces = ["std", "_GLIBCXX_STD"]
" automatically open and close the popup menu / preview window
au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif
set completeopt=menuone,menu,longest,preview
