# History file parameters (path to the history file, size of the history etc)
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000


# Allow changing directory by its name, w/o cd
setopt auto_cd

# Allow piping to multiple outputs
setopt multios

# 
setopt extended_glob

# Path to my zsh configuration.
ZSH=$HOME/Config/dotfiles/zsh
# Path to additional config files
ZSH_CONFIG=$ZSH/config
# Path to zsh plugins
ZSH_PLUGINS=$ZSH/plugins


# Add /usr/local/bin to the path, so we can enable Homebrew & all its packages
export PATH=/usr/local/bin:$PATH
export PATH=$PATH:$ANDROID_SDK_ROOT/tools

export EDITOR=vim
export SHELL=zsh

# Load all of the config files in $ZSH/lib that end in .zsh
# TIP: Add files you don't want in git to .gitignore
for config_file ($ZSH_CONFIG/*.zsh) source $config_file

# Load and run compinit for the tab completion
autoload -U compinit
compinit -i

# Load all of the plugins 
plugins=(ant brew bundler django gem git git-flow github heroku npm pip pow python rails3 rvm sublime thor vagrant vundle)
for plugin ($plugins); do
  if [ -f $ZSH/plugins/$plugin/$plugin.plugin.zsh ]; then
    source $ZSH/plugins/$plugin/$plugin.plugin.zsh
  fi
done

ZSH_THEME="xenocid"

# Load the theme
source "$ZSH/themes/$ZSH_THEME.zsh-theme"

# use .localrc for settings specific to one system
[[ -f ~/.localrc ]] && . ~/.localrc

# Load the TMuxinator
[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator
#
# # Load the RVM
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
